# Usa a imagem oficial do Python como base
FROM python:3.12-slim

# Define o diretório de trabalho
WORKDIR /app

RUN apt-get update 
RUN apt-get install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils

#download and install chrome
RUN apt-get install -y wget 
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install



#install python dependencies
COPY requirements.txt requirements.txt 
RUN pip install -r ./requirements.txt 

# Define a variável de ambiente para apontar para o Chrome instalado
ENV CHROME_BIN="/usr/bin/google-chrome"

# Copia os arquivos do projeto para dentro do container
COPY . .

#dá permissão ao script (não sei se era necessário, mas não estava iniciando anteriormente sem isso.)
RUN chmod +x main.py

# Define o comando para executar o script
CMD ["python", "main.py"]
